// @generated by handbook/bin/gen-related-tools.mjs from handbook/tools.json — DO NOT EDIT.
// To change this tool's related-tools section, edit tools.json (this tool's `related[]`, or the
// referenced tools' hub.icon/hub.card), then run `node handbook/bin/gen-related-tools.mjs strip-tracking`
// (or with no arg to regenerate every active tool) and commit the result.

export interface RelatedToolCard {
  slug: string;
  icon: string;
  name: Record<string, string>;
  desc: Record<string, string>;
}

/** Curated related tools (Issue #177) — same hub.group baseline + genuine cross-group workflow ties. */
export const RELATED_TOOLS: RelatedToolCard[] = [
  {
    "slug": "qr-generator",
    "icon": "🔳",
    "name": {
      "en": "QR Code Generator",
      "ja": "QRコード生成",
      "zh": "生成二维码",
      "de": "QR-Code erstellen",
      "es": "Generar código QR"
    },
    "desc": {
      "en": "Turn text or a URL into a static QR code — no redirect or tracking layer.",
      "ja": "テキストやURLを静的QRコードに変換。リダイレクトや追跡層なし。",
      "zh": "将文本或网址转换为静态二维码 — 没有重定向或追踪层。",
      "de": "Wandelt Text oder eine URL in einen statischen QR-Code um — ohne Weiterleitung oder Tracking.",
      "es": "Convierte texto o una URL en un código QR estático — sin redirección ni rastreo."
    }
  },
  {
    "slug": "har-viewer",
    "icon": "🕸️",
    "name": {
      "en": "HAR Viewer",
      "ja": "HARビューア",
      "zh": "HAR 查看器",
      "de": "HAR-Viewer",
      "es": "Visor de HAR"
    },
    "desc": {
      "en": "Inspect a .har network capture — requests, timing waterfall, headers — with warnings for exposed tokens.",
      "ja": ".harネットワークキャプチャを閲覧。リクエスト・タイミング・ヘッダーに加え、露出したトークンを警告。",
      "zh": "查看 .har 网络抓包记录 — 请求、时间瀑布图、请求头 — 并对暴露的令牌发出警告。",
      "de": "Untersuche eine .har-Netzwerkaufzeichnung — Anfragen, Zeitverlauf, Header — mit Warnungen vor offengelegten Tokens.",
      "es": "Inspecciona una captura de red .har — solicitudes, cronología, cabeceras — con avisos de tokens expuestos."
    }
  }
];

/** This tool's own engineering-notes article slug (/blog/<slug>/), or null if none is published yet. */
export const BLOG_SLUG: string | null = 'strip-tracking';
